ALTER TABLE Equipamento ALTER COLUMN link TYPE TEXT;
ALTER TABLE Videoaula ALTER COLUMN descricao TYPE TEXT;
ALTER TABLE Canal ALTER COLUMN bio TYPE TEXT;
ALTER TABLE Patrocinador ALTER COLUMN link TYPE TEXT;